### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by CCTV14** [YuHuaOu/electron-print#5]
找不到端口45656

**Comment by YuHuaOu** [comment]
> 找不到端口45656

能具体描述一下情况吗？
在应用上开启服务后，调用接口时，地址为 http://localhost:45656 或者 http://localhost:45656，是这样调用吗？

**Comment by CCTV14** [comment]
端口问题已解决，目前支持打印pdf文件吗

**Comment by CCTV14** [comment]
好的，能监听到打印机的状态吗。比如缺纸，正在打印，脱机

**Comment by YuHuaOu** [comment]
> 好的，能监听到打印机的状态吗。比如缺纸，正在打印，脱机

1. 正在打印，如果一直在调打印的接口的话，会有一个打印队列的排序，发过去的请求会一直在pending，等待打印完成后才会响应结果(将打印成功/失败的结果返回)，按照队列的顺序打印，所以如果接口还没内容返回的话，就可以理解为打印机正在执行打印(或者正在获取下载的文件资源)。
2. 缺纸，脱机这两个状态还没处理，估计需要额外引入一些工具库来获取

**Comment by YuHuaOu** [comment]
!
