### ISSUE TITLE
執行下載列印過程失敗

### ISSUE THREAD

**Issue by shengkinng** [YuHuaOu/electron-print#6]
下載時出現執行下載列印過程失敗: RequestError: certificate has expired
但我的pdf url 可以正常訪問..找不到原因

**Comment by shengkinng** [comment]
> > 下載時出現執行下載列印過程失敗: RequestError: certificate has expired 但我的pdf url 可以正常訪問..找不到原因
> 
> 
> 
> 应该是这个pdf资源的ssl证书过期了，在使用 download 这个库下载的时候就会抛出异常。
> 
> 你可以在调用打印程序的接口中传入 downloadOptions
> 
> ```javascript
> 
> // 例如:
> 
> // 用 rejectUnauthorized 来控制证书的验证行为
> 
> fetch(`${url}`, { method: 'POST', body: { fileUrl: fileUrl, downloadOptions: { rejectUnauthorized: false } } })
> 
> ```

可是我單純使用 pdf url https://xx.xxx.xx/pdf/xxx.pdf 在瀏覽器是可以打開呢

**Comment by YuHuaOu** [comment]
浏览器会默认信任过期证书，能去查看资源，虽然说证书过期了，但是有的浏览器为了方便查看网站或者资源，可能会显示一个警告的提示，用于指出存在安全风险（可以手动选择是否忽略提示）。
但是在用 nodejs 去下载这个过期的资源的时候，回去严格验证ssl证书的有效性（还有是否过期）。
你可以试着加入 downloadOptions: { rejectUnauthorized: false }，去忽略证书验证

**Comment by shengkinng** [comment]
> 浏览器会默认信任过期证书，能去查看资源，虽然说证书过期了，但是有的浏览器为了方便查看网站或者资源，可能会显示一个警告的提示，用于指出存在安全风险（可以手动选择是否忽略提示）。
> 
> 但是在用 nodejs 去下载这个过期的资源的时候，会去严格验证ssl证书的有效性（还有是否过期）。
> 
> 你可以试着加入 downloadOptions: { rejectUnauthorized: false }，去忽略证书验证

那我該在哪引入這個參數呢?

download(url,pdfname,downloadOptions)

這樣？

**Comment by shengkinng** [comment]
正常 ！ download(data, strFileName, strMimeType）

**Comment by YuHuaOu** [comment]
在调用打印服务的接口的时候，传入 downloadOptions 就好了。
```javascript
// 以使用 fetch api 去调用打印服务的接口为例：

// 打印服务接口源地址
const printOriginUrl = 'http://localhost:45656/print'

// 链接资源地址
const fileUrl = 'https://xxx'

fetch(printOriginUrl, { 
    method: 'POST',
    body: {
        fileUrl: fileUrl,
        downloadOptions: {
             rejectUnauthorized: false 
        }
    }
})
```

其中，downloadOptions 这个选项是用于传给 download 这个nodejs下载库去下载资源的。

**Comment by shengkinng** [comment]
我嘗試你的方法也是無法解決,
但我發現 我使用 /preview 是可以打開檔案的就唯獨 /print

**Comment by YuHuaOu** [comment]
> 我嘗試你的方法也是無法解決, 但我發現 我使用 /preview 是可以打開檔案的就唯獨 /print

可以看下具体代码吗？

**Comment by shengkinng** [comment]
是的, 約幾個月前都還可行, 是最近才無法.. 你要看哪一段呢?
因為我有些地方有修改, 是否可指引哪一段關鍵code 我放上來 thx!!

**Comment by shengkinng** [comment]
![2023-10-23_175204](https://github.com/YuHuaOu/electron-print/assets/40712030/92c6dc6e-abbd-46a8-aa89-11dd62fdb587)

**Comment by YuHuaOu** [comment]
把传参放到body里面去，不要带在 url 上，因为 /print 的这个接口支持两种方式，一种是 fileUrl 带在 url 上（以拼接的方式），第二中是将传参放到请求 body，你可以在 README.md 上写的演示实例中，使用这个
 
![image](https://github.com/YuHuaOu/electron-print/assets/43210995/e0c41dd8-5ecd-44d2-917a-2c7c5df9592a)

**Comment by YuHuaOu** [comment]
downloadOptions 仅支持第二种方式，不支持第一种带在 url 上拼接的方式。

**Comment by YuHuaOu** [comment]
可以了吗，朋友，还是不行的话可以留个联系方式看看

**Comment by YuHuaOu** [comment]
加个微信看下

**Comment by shengkinng** [comment]
id: momopuffer
